from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Optional, Protocol, runtime_checkable

import numpy as np


@runtime_checkable
class TrackerProtocol(Protocol):
    def update(self, dets: np.ndarray, frame: np.ndarray) -> np.ndarray: ...


@runtime_checkable
class ModelRegistryProtocol(Protocol):
    def list_models(self) -> list: ...
    def get_model(self, name: str) -> Optional[object]: ...
    def get_detector_path(self, name: str) -> Optional[Path]: ...
    def get_reid_path(self, name: str) -> Optional[Path]: ...
    def scan(self) -> None: ...


@runtime_checkable
class SessionStoreProtocol(Protocol):
    def create(self, session_id: str, detector, tracker, config) -> object: ...
    def get(self, session_id: str) -> Optional[object]: ...
    def delete(self, session_id: str) -> bool: ...
    def list_ids(self) -> List[str]: ...
    def increment_frame(self, session_id: str) -> int: ...
    def set_annotated_frame(self, session_id: str, jpeg_bytes: bytes) -> None: ...
    def set_track_count(self, session_id: str, count: int) -> None: ...
    def get_stats(self, session_id: str) -> Optional[Dict]: ...
